project:
  type: book
  output-dir: docs

book:
  title: "ESM240 – Climate Change Biology: From Models to Applications"
  subtitle: "From Models to Applications"
  author: "Isaac Brito-Morales"
  date: "October 9, 2025"
  description: "A professional-training eBook for master’s students to understand, locate, and use climate model data for marine conservation and applied research."
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/IsaakBM/ESM_240
  repo-actions: [issue]
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 01_preparation.qmd
    - 02_set_up.qmd
    - 03_cmip6_models.qmd
    - 05_ncRaster.qmd
    - references.qmd

bibliography: references.bib

comments:
  hypothesis: true
  
format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 400px
      body-width: 700px
      margin-width: 500px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt

editor: visual