project:
  type: book
  output-dir: docs

book:
  title: "ESM240 Week 4: Climate-smart marine conservation"
  author: "Isaac Brito-Morales"
  date: "10/30/2023"
  sidebar:
    style: docked
    background: light
  search: true
  repo-url: https://github.com/IsaakBM/ESM_240
  repo-actions: [issue]
  downloads: [pdf]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 01_preparation.qmd
    - 02_set_up.qmd
    - 03_cmip6_models.qmd
    - 04_climate_data.qmd
    - 05_ncRaster.qmd
    - 06_equalGrid.qmd
    - 07_climatePUs.qmd
    - references.qmd

bibliography: references.bib

comments:
  hypothesis: true
  
format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 400px
      body-width: 700px
      margin-width: 500px
      gutter-width: 1.5rem
  pdf:
    documentclass: scrreprt

editor: visual